# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- test7

pool:
  vmImage: 'Hosted'

steps:
- script: echo Hello, world!!!!!!!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

schedules:
- cron: "10 0 * * *"
  displayName: Scheduled
  branches:
    include:
    - master
  always: true

pr:
  branches:
    include:
    - master
  paths:
    include:
    - sdk/keyvault/
