# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: default
resources:
  repositories:
  - repository: self
    type: github
    name: Prachiti9/private 
    endpoint: p1
    ref: 'refs/heads/master'

steps:
- script: echo Hello, world!!
  displayName: 'Run a one-line script'

schedules:
  - cron: "0 0 * * *"
    branches:
      include:
        - master
    displayName: once everyday
